FAC-Sixteen/groundworks-client

- src/App.js
- src/components/Homepage/Info/Info.css
- src/components/Homepage/Info/Info.js
> create info component

- src/App.js
- src/components/Homepage/Header/Header.css
- src/components/Navbar/NavBar.js
> style header

- src/App.js
- src/routes/ClientDashboard.js
- src/routes/ClientSignup.js
- src/routes/Home.js
- src/routes/Login.js
- src/routes/NewBrief.js
- src/routes/StudentDashboard.js
- src/routes/StudentSignup.js
- webpack.config.js
- App.js now the central front-end Router
- Homepage code now in src/routes/Home
- Routes folder created in client with 7 React pages
- Need to add components to the pages in Routes folder
- webpack updated to allow front end routing
Relates #56
> Add React router, change files

- src/components/LoginRegister/LoginPortal/LoginPortal.js
- src/components/LoginRegister/RegisterPortal/RegisterPortal.css
- src/components/LoginRegister/RegisterPortal/RegisterPortal.js
> add register form

- src/components/LoginRegister/LoginPortal/LoginPortal.js
- src/components/LoginRegister/RegisterPortal/RegisterPortal.js
- src/components/Navbar/NavBar.js
- src/routes/Join.js
- src/routes/Login.js
> Link login page

- package.json
- src/components/clientSignupForm/ClientSignupForm.css
- src/components/clientSignupForm/ClientSignupForm.js
- src/routes/ClientSignup.js
- yarn.lock
> Create Client Sign Up Form

- public/index.html
- Description, Author, etc
Relates #5
> Add meta tags to index.html

- package.json
- public/index.html
- src/App.js
- webpack.config.js
- yarn.lock
- link bundled js and html files for deployment
- Relates #5
-
> Update linter, webpack

- src/components/ClientDashboard/ClientProfileCard/ClientProfileCard.js
- src/components/StudentDashboard/ShortStudentProfileCard/ShortStudentProfileCard.js
- src/components/clientSignupForm/ClientSignupForm.js
- Auto query and render/populate card on load with useEffect
- Relates #86
> Connect Student/Client profile card to database

- src/components/ClientDashboard/LongStudentProfileCard/LongStudentProfile.js
- src/components/ClientDashboard/LongStudentProfileCard/LongStudentProfileCard.js
> render student data

- src/components/StudentDashboard/NewJobCard/NewJobCard.js
> fetch job brief

- src/components/LoginRegister/RegisterPortal/RegisterPortal.css
- src/components/LoginRegister/RegisterPortal/RegisterPortal.js
- src/components/StudentDashboard/CompletedJobCard/StudentCompletedJobCard.js
- src/components/StudentDashboard/CurrentJobCard/CurrentJobCard.js
- src/components/StudentDashboard/NewJobCard/NewJobCard.js
- src/components/StudentDashboard/ShortStudentProfileCard/ShortStudentProfile.js
- src/components/StudentDashboard/ShortStudentProfileCard/ShortStudentProfileCard.js
- src/components/StudentDashboard/StudentJobsToggle/StudentJobsToggle.js
> Update Student profile cars and RegisterPortal

- src/components/Homepage/Founders/Founders.js
- src/components/Homepage/Header/Header.js
- src/components/StudentDashboard/NewJobCard/NewJobCard.css
- React Link
- Update CSS on New job card to match the others
- Relates #115
> Update links on Home and Navbar

- src/components/Footer/Footer.css
- src/routes/StudentDashboard.js
> Remove footer on student dashboard

- Procfile
- package.json
- src/components/LoginRegister/RegisterPortal/RegisterPortal.js
- tools/build.js
- tools/buildHtml.js
- tools/publicServer.js
- webpack.config.prod.js
- yarn-error.log
- yarn.lock
Testing deployment on front-end heroku
> Deployment changes to front-end heroku

- package.json
- Testing deployment
- Relates #127
> Add Heroku build scripts to package json

- package.json
- yarn-error.log
- yarn.lock
> Update packages for deployment

- package.json
- yarn-error.log
> Update script for deployment

- Procfile
- required to run yarn start
- Relates #125
> Add Procfile for Heroku deployment

- Procfile
- package.json
- yarn-error.log
- Heroku not finding after build
- Relates #125
-
> Move webpack-dev-server from devDependencies to dependencies

- package.json
- yarn.lock
- Heroku not finding after build
- Relates #125
> Move webpack-cli to dependencies from devDependencies

- package.json
- yarn.lock
- Heroku not finding after build
- Relates #125
-
> Move webpack to dependencies

- package.json
> Remove postinstall script from package.json

- package.json
- Causing error
- Relates #125
-
> Remove heroku-postbuild script

- package.json
- yarn-error.log
> Move html-webpack-plugin to dependencies

- .gitignore
- src/App.js
- src/components/StudentDashboard/CompletedJobCard/StudentCompletedJobCard.js
- src/components/StudentDashboard/CurrentJobCard/CurrentJobCard.js
- src/components/StudentDashboard/NewJobCard/NewJobCard.js
- src/components/StudentDashboard/ShortStudentProfileCard/ShortStudentProfile.js
- src/components/StudentDashboard/ShortStudentProfileCard/ShortStudentProfileCard.js
- src/components/StudentDashboard/StudentJobsToggle/StudentJobsToggle.js
- src/routes/StudentDashboard.js
- webpack.config.js
- Will query DB once on page load and pass to all components
Relates #96
> Pass props with student data to all components in dashboard
